### ISSUE TITLE
Issue with permissions on Ubuntu - Node was not installed

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-local-chain#1]
**Bug Description**
Running the lc1c app on Ubuntu, as it is now node can't be installed automatically.

**Steps to Reproduce**
1. Download the built package from Github
2. Install the tool and start it.
3. Select Install the node.

**Expected Result**
Application will ask the user for necessary permissions to install the node, after user confirms the pop up, the node should be installed, it should be possible to run the local chain after installation of the node and genesis creator are done.

**Actual Result**
Even though the installation button turns green as the installation was completed, the node was not installed.

**Possible workaround**
Install the node from the deb package using apt. Then in the usr/bin rename the node to concordium-node.
Make sure the node you have installed has stopped before starting lc1c

**Notes**
As concluded, the root cause of the issue are permissions. 

**Versions**
- Software Version:0.1.0
- OS: Ubuntu

**Comment by mh-concordium** [comment]
I have tried to install the new tool and the node and now the permission windows pops up but after inserting password installation of the node fails. Tested in latest released version.
file:///home/mh/Screencasts/Screencast%20from%2011-14-2023%2010:07:02%20AM.webm

**Comment by gachouchani1999** [comment]
@mh-concordium turns out there is a difference in GLIBC version between different Ubuntu versions. We are pushing a new build that should solve this to all Ubuntu versions.
