### ISSUE TITLE
Chain starts from genesis on protocol version 5

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-local-chain#10]
**Bug Description**
Chain starts from genesis on protocol version 5 while there is a newer version with different parameters.

**Steps to Reproduce**
Start lc1c.
Start a chain in easy mode.

**Expected Result**
Chain should start from the latest protocol version (currently protocol 6).

**Actual Result**
Chan starts from protocol version 5.

**Versions**
- Software Version: 0.1.0

**Comment by abizjak** [comment]
This should be addressed in the next version. The default genesis is p6.

**Comment by EmilLa1** [comment]
Fixed in https://github.com/Concordium/concordium-local-chain/pull/27
