### ISSUE TITLE
Local chain doesn't start on Windows

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-local-chain#15]
**Bug Description**
Attempt to start a local chain failed. Looking at the LC1C dashboard on the accounts tab, it seems that genesis data is not found since the accounts are not listed.

**Steps to Reproduce**

1. If previous node versions exist on your Windows machine delete it.
2. Start the tool, install the node and try to run a local chain in Easy mode.

**Expected Result**
Local chain should start.

**Actual Result**
Local chain doesn't start.

Video:

https://github.com/Concordium/concordium-local-chain/assets/98821384/e3803d23-564a-4640-b671-c2ce777ab610

**Versions**
- Software Version: 0.1.1
- OS: Windows

**Comment by mh-concordium** [comment]
@EmilLa1 It is not possible to start a chain in 0.1.3.

**Comment by EmilLa1** [comment]
Fixed by https://github.com/Concordium/concordium-local-chain/pull/32
