### ISSUE TITLE
Installation of the tool for the first time hangs while installing genesis-creator

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-local-chain#17]
**Bug Description**
It looks as the tool is not responding while installing the tool for the first time. This appears while step "Install Genesis Creator" is being executed. If user just waits and doesn't forcefully quit the application, the installation was successful. So installation was ok, it is just that application should not appear as non responsive while user is suppose to wait.

**Steps to Reproduce**
1. If any previous installation was done, make sure all the applications and files related are removed. Specifically remove genesis-creator from `~/.cargo/bin`
2. Run through all the installation steps.

**Actual Result**
During installation of the genesis-creator, user will see the following warning
![image](https://github.com/Concordium/concordium-local-chain/assets/98821384/d3f53ef0-cca8-4345-9f97-96a1d7680601)

**Versions**
- Software Version: 0.1.1
- OS: Ubuntu

**Comment by mh-concordium** [comment]
Maybe we could have challenges with genesis-creator versions in the future. What do you think? @abizjak

**Comment by gachouchani1999** [comment]
Yes this is why we decided to opt in for installations in the first place.

**Comment by gachouchani1999** [comment]
#20 fixes this issue
