### ISSUE TITLE
Local chain stops around specific height every time

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-local-chain#5]
**Bug Description**
Just after running the tool in EASY mode, it seems that the chain stops at height 47 or 48.

**Steps to Reproduce**

1. Install the node and the tool
2. Start the chain with the workaround for permissions.
3. Let the chain run for 50 blocks.

**Expected Result**
Chain continues to run, it doesn't stop.

**Actual Result**
Chain stops at the height of 47 or 48.

**Notes**
Looking at the node and querying it wih concordium client on grpc2 port 20100, it indeed stops at height 48. The node seems to be responsive.

I have tried to run the local chain having one baker only with the node version 5.4.2 with the genesis that I have created starting from protocol 5 and it was running past the height 100.
I have also tried to runt he local chain having one baker only with the node version 6.1.7 with the genesis that I have created starting from protocol 6 and it was running past the height 2000. 

**Versions**
- Software Version: 0.1.0
- OS: Ubuntu

I have added the issue video as well:

[Screencast from 11-07-2023 01:50:40 PM.webm](https://github.com/Concordium/concordium-local-chain/assets/98821384/f0d4b000-703a-4d02-b3f5-074c547a88d7)

**Comment by mh-concordium** [comment]
The same issue appears on MacOs, chain stops at height 50.

**Comment by mh-concordium** [comment]
The same issue as above commented was noticed on Ubuntu.
![image](https://github.com/Concordium/concordium-local-chain/assets/98821384/07cb3dc8-f7d6-4a8d-8d6a-7b224b8c67b7)

**Comment by EmilLa1** [comment]
Fixed via https://github.com/Concordium/concordium-local-chain/pull/27
