### ISSUE TITLE
If the node was not installed or can't be found, user should not be able to proceed to the Genesis Builder

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-local-chain#6]
**Bug Description**
In case the node installation have failed, user should not be able to attempt to launch the chain. User should not be able to proceed to the genesis builder if the node was not installed.

**Steps to Reproduce**

1. Start the tool, follow the steps by their numerical order.
2. Select install Concordium Node -> turns green - Node Installed!
4. Select  verify Node installation -> fails
5. Select Install Genesis Creator -> turns green - Genesis Creator Installed!
6. Go to Genesis builder

**Expected Result**
The last step should not be available since the installation has failed.

**Actual Result**
User can proceed and try to start a chain but chain doesn't start. It looks as the application hangs.

**Versions**
- Software Version: 0.1.0

**Comment by EmilLa1** [comment]
This is resolved via https://github.com/Concordium/concordium-local-chain/pull/11 and the changes in https://github.com/Concordium/concordium-local-chain/pull/27.
