### ISSUE TITLE
Possibility to select to run a chain from known state

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-local-chain#8]
**Description**
It would be a nice feature for developer to be able to select if they want to start a new fresh chain from a new state or the last chain they used from the known state.

Currently, every time lc1c tool is started, the chain starts from a new state.

**Steps to Reproduce**
Start lc1c.
Start a chain in easy mode.

**Expected Result**
User should be able to select to start a new chain from 0 or just continue on the previous chain from the known state. If user selects to continue on the previous chain, chain should just start and user should not need to select the level of expertise again.

**Actual Result**
Chain always starts from a new state.

**Versions**
- Software Version
- OS
- Browser
- Mobile device, if applicable

**Comment by gachouchani1999** [comment]
<img width="1724" alt="Screen Shot 2023-11-09 at 12 25 49 AM" src="https://github.com/Concordium/concordium-local-chain/assets/73434909/c60969dd-e616-434d-90f8-844360cbd220">
There is the option to "Load Config" which allows to load a previous chain from its last state and continue development. 

Just verifying if this option does not show?

**Comment by mh-concordium** [comment]
I don't see that option on Ubuntu. 
![image](https://github.com/Concordium/concordium-local-chain/assets/98821384/12b8227a-1584-4d54-82fb-2e8dfc13f80e)

**Comment by mh-concordium** [comment]
It also looks like your UI is a bit different like letters are white, mine are black. I don't know if it matters but could it be that you are looking at the branch that is further then what concordium-lc1c_0.1.0_amd64.deb was built from?

**Comment by mh-concordium** [comment]
@gachouchani1999 Sorry for misunderstanding. I have just now realized that I would have to select "Load Config" to be able to start the chain that was previously running. My feeling was that "Load Config" would be for me to load my own genesis data if I want so I have't tried the "Load Config" option before. I will consult with my team to see if we should change anything regarding this.

I confirm that the dropdown menu appears once I selected "Load Config" button. We will be able to test it.

**Comment by mh-concordium** [comment]
Okay, thank you. I think for that reason it would be nice to add this one to the next build https://github.com/Concordium/concordium-local-chain/issues/2

**Comment by gachouchani1999** [comment]
Should we close this?

**Comment by mh-concordium** [comment]
We wanted to propose slight change to the UI flow in regarding to this if possible.

Ideally, if user have had the chain running before, right after starting the app, user would be able to just decide to run the previous chain or start a new one. If previous chain is selected then the app would just continue from the previous chain. If user selects to start a new chain, then user would be routed to the page with expertise levels.

In case of that UI change, there would probably need to be some UI changes as well that would allow user to navigate between those views. For example,  in case user first continues from previous chain but then decides to start a new chain. Then, user would, after killing the chain have to be routed to the page where the choice is presented to either start a new chain or continue from previous chain.

**Comment by EmilLa1** [comment]
The UI has been simplified and changed quite a bit due to https://github.com/Concordium/concordium-local-chain/pull/27, so not sure if this is relevant anymore. 

If the ux should change, then please open an issue stating your proposed flow.
